FROM centos:latest
MAINTAINER pinenut
ENV REFRESHED_AT 2019-01-29 10:45

ADD jdk-8u91-linux-x64.tar.gz /java/
COPY US_export_policy.jar /java/jdk1.8.0_91/jre/lib/security/
COPY local_policy.jar /java/jdk1.8.0_91/jre/lib/security/

ENV JAVA_HOME /java/jdk1.8.0_91/
ENV JRE_HOME ${JAVA_HOME}/jre
ENV CLASSPATH .:${JAVA_HOME}/lib:${JRE_HOME}/lib
ENV PATH ${JAVA_HOME}/bin:$PATH
ENV JAVA_TOOL_OPTIONS -Dfile.encoding=UTF-8
CMD mkdir /etc/jing